# -*- coding: utf-8 -*-
"""FaseII_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXOn_JFYkeH0FmrRhUm2DgJp_4oJCntu
"""

# =====================================================
# TITANIC DATASET - AUTOGLUON AUTOML
# =====================================================

# Instalar AutoGluon
!pip -q install autogluon
#!pip install -q autogluon.tabular==1.4.0

import pandas as pd
from google.colab import files

from autogluon.tabular import TabularPredictor

# -----------------------------------------------------
# Cargar Dataset
# -----------------------------------------------------

df = pd.read_csv("train.csv")

print(df.head())

print(df.info())

# -----------------------------------------------------
# Eliminar columnas poco útiles
# -----------------------------------------------------

df = df.drop(
    columns=[
        "PassengerId",
        "Name",
        "Ticket",
        "Cabin"
    ]
)

# -----------------------------------------------------
# Separar entrenamiento y prueba
# -----------------------------------------------------

train = df.sample(frac=0.8, random_state=42)

test = df.drop(train.index)

print()

print("Train:", train.shape)

print("Test :", test.shape)

# -----------------------------------------------------
# Entrenar AutoML
# -----------------------------------------------------

predictor = TabularPredictor(
    label="Survived",
    eval_metric="accuracy"
).fit(
    train_data=train,
    presets="medium_quality",
    hyperparameters={
        "GBM": {},      # LightGBM
        "RF": {},       # Random Forest
        "XT": {},       # Extra Trees
        "CAT": {},      # CatBoost
        "XGB": {}       # XGBoost
    }
)

# -----------------------------------------------------
# Mostrar Ranking
# -----------------------------------------------------

leaderboard = predictor.leaderboard(test)

print(leaderboard)

# -----------------------------------------------------
# Mejor modelo
# -----------------------------------------------------

print()

print("Mejor modelo:")

print(predictor.model_best)

# -----------------------------------------------------
# Exactitud
# -----------------------------------------------------

performance = predictor.evaluate(test)

print()

print(performance)

# -----------------------------------------------------
# Guardar Predictor
# -----------------------------------------------------

predictor.save()

print()

print("Modelo guardado correctamente.")

# -----------------------------------------------------
# Descargar carpeta del modelo
# -----------------------------------------------------

import shutil

shutil.make_archive(
    "TitanicModel",
    "zip",
    predictor.path
)

files.download("TitanicModel.zip")