{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4",
      "authorship_tag": "ABX9TyNSZvn0mJjepJ56Rm/yMceO",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Rams302/TitanicAPI/blob/main/monitoring/monitor.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ==========================================================\n",
        "# Monitoring Engine\n",
        "# TitanicAPI MLOps\n",
        "# ==========================================================\n",
        "\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "\n",
        "import os\n",
        "\n",
        "import json\n",
        "\n",
        "from datetime import datetime\n",
        "\n",
        "from statistics import mean\n",
        "\n",
        "\n",
        "\n",
        "class ModelMonitor:\n",
        "\n",
        "\n",
        "    def __init__(self):\n",
        "\n",
        "\n",
        "        self.log_file = (\n",
        "\n",
        "            \"monitoring/predictions.log\"\n",
        "\n",
        "        )\n",
        "\n",
        "\n",
        "        self.metrics_file = (\n",
        "\n",
        "            \"monitoring/current_model_metrics.json\"\n",
        "\n",
        "        )\n",
        "\n",
        "\n",
        "        self.history_file = (\n",
        "\n",
        "            \"monitoring/metrics_history.json\"\n",
        "\n",
        "        )\n",
        "\n",
        "\n",
        "\n",
        "    # ------------------------------------------------------\n",
        "    # Leer configuración\n",
        "    # ------------------------------------------------------\n",
        "\n",
        "    def load_metrics_config(self):\n",
        "\n",
        "\n",
        "        with open(\n",
        "\n",
        "            self.metrics_file,\n",
        "\n",
        "            \"r\",\n",
        "\n",
        "            encoding=\"utf-8\"\n",
        "\n",
        "        ) as file:\n",
        "\n",
        "\n",
        "            return json.load(file)\n",
        "\n",
        "\n",
        "\n",
        "    # ------------------------------------------------------\n",
        "    # Generar ID ejecución\n",
        "    # ------------------------------------------------------\n",
        "\n",
        "    def execution_number(self):\n",
        "\n",
        "\n",
        "        if not os.path.exists(\n",
        "\n",
        "            self.history_file\n",
        "\n",
        "        ):\n",
        "\n",
        "            return 1\n",
        "\n",
        "\n",
        "\n",
        "        with open(\n",
        "\n",
        "            self.history_file,\n",
        "\n",
        "            \"r\",\n",
        "\n",
        "            encoding=\"utf-8\"\n",
        "\n",
        "        ) as file:\n",
        "\n",
        "\n",
        "            data=json.load(file)\n",
        "\n",
        "\n",
        "\n",
        "        return len(data)+1\n",
        "\n",
        "\n",
        "\n",
        "    # ------------------------------------------------------\n",
        "    # Evaluación individual\n",
        "    # ------------------------------------------------------\n",
        "\n",
        "    def evaluate_latency(self, latency):\n",
        "\n",
        "\n",
        "        config = self.load_metrics_config()\n",
        "\n",
        "\n",
        "        limit = (\n",
        "\n",
        "            config[\"thresholds\"]\n",
        "\n",
        "            [\"max_latency_seconds\"]\n",
        "\n",
        "        )\n",
        "\n",
        "\n",
        "\n",
        "        if latency > limit:\n",
        "\n",
        "\n",
        "            return (\n",
        "\n",
        "                \"EXCEEDED\",\n",
        "\n",
        "                f\"ADVERTENCIA: latencia superior al límite de {limit} segundos\"\n",
        "\n",
        "            )\n",
        "\n",
        "\n",
        "\n",
        "        return (\n",
        "\n",
        "            \"NORMAL\",\n",
        "\n",
        "            None\n",
        "\n",
        "        )\n",
        "\n",
        "\n",
        "\n",
        "    # ------------------------------------------------------\n",
        "    # Crear log\n",
        "    # ------------------------------------------------------\n",
        "\n",
        "    def write_prediction_log(\n",
        "\n",
        "        self,\n",
        "\n",
        "        request_id,\n",
        "\n",
        "        input_data,\n",
        "\n",
        "        prediction,\n",
        "\n",
        "        latency,\n",
        "\n",
        "        status\n",
        "\n",
        "    ):\n",
        "\n",
        "\n",
        "\n",
        "        execution = self.execution_number()\n",
        "\n",
        "\n",
        "\n",
        "        latency_status, alert = (\n",
        "\n",
        "            self.evaluate_latency(latency)\n",
        "\n",
        "        )\n",
        "\n",
        "\n",
        "\n",
        "        log = {\n",
        "\n",
        "\n",
        "            \"timestamp\":\n",
        "\n",
        "            datetime.now().isoformat(),\n",
        "\n",
        "\n",
        "            \"execution_id\":\n",
        "\n",
        "            execution,\n",
        "\n",
        "\n",
        "            \"request_id\":\n",
        "\n",
        "            request_id,\n",
        "\n",
        "\n",
        "            \"event_type\":\n",
        "\n",
        "            \"MODEL_PREDICTION\",\n",
        "\n",
        "\n",
        "            \"status\":\n",
        "\n",
        "            status,\n",
        "\n",
        "\n",
        "            \"input_data\":\n",
        "\n",
        "            input_data,\n",
        "\n",
        "\n",
        "            \"model_response\":\n",
        "\n",
        "            prediction,\n",
        "\n",
        "\n",
        "            \"performance\":\n",
        "\n",
        "            {\n",
        "\n",
        "\n",
        "                \"latency_seconds\":\n",
        "\n",
        "                latency\n",
        "\n",
        "            },\n",
        "\n",
        "\n",
        "            \"monitoring\":\n",
        "\n",
        "            {\n",
        "\n",
        "\n",
        "                \"latency_status\":\n",
        "\n",
        "                latency_status,\n",
        "\n",
        "\n",
        "                \"alert\":\n",
        "\n",
        "                alert\n",
        "\n",
        "            }\n",
        "\n",
        "\n",
        "        }\n",
        "\n",
        "\n",
        "\n",
        "        with open(\n",
        "\n",
        "            self.log_file,\n",
        "\n",
        "            \"a\",\n",
        "\n",
        "            encoding=\"utf-8\"\n",
        "\n",
        "        ) as file:\n",
        "\n",
        "\n",
        "            file.write(\n",
        "\n",
        "                \"\\n\"\n",
        "\n",
        "                + \"=\"*70\n",
        "\n",
        "                + \"\\n\"\n",
        "\n",
        "            )\n",
        "\n",
        "\n",
        "            file.write(\n",
        "\n",
        "                json.dumps(\n",
        "\n",
        "                    log,\n",
        "\n",
        "                    indent=4,\n",
        "\n",
        "                    ensure_ascii=False\n",
        "\n",
        "                )\n",
        "\n",
        "            )\n",
        "\n",
        "\n",
        "\n",
        "            file.write(\n",
        "\n",
        "                \"\\n\"\n",
        "\n",
        "                + \"=\"*70\n",
        "\n",
        "                + \"\\n\"\n",
        "\n",
        "            )\n",
        "\n",
        "\n",
        "\n",
        "        self.save_history(log)\n",
        "\n",
        "\n",
        "\n",
        "    # ------------------------------------------------------\n",
        "    # Guardar histórico\n",
        "    # ------------------------------------------------------\n",
        "\n",
        "    def save_history(self, log):\n",
        "\n",
        "\n",
        "        history=[]\n",
        "\n",
        "\n",
        "\n",
        "        if os.path.exists(\n",
        "\n",
        "            self.history_file\n",
        "\n",
        "        ):\n",
        "\n",
        "\n",
        "            with open(\n",
        "\n",
        "                self.history_file,\n",
        "\n",
        "                \"r\",\n",
        "\n",
        "                encoding=\"utf-8\"\n",
        "\n",
        "            ) as file:\n",
        "\n",
        "\n",
        "                history=json.load(file)\n",
        "\n",
        "\n",
        "\n",
        "        history.append(log)\n",
        "\n",
        "\n",
        "\n",
        "        with open(\n",
        "\n",
        "            self.history_file,\n",
        "\n",
        "            \"w\",\n",
        "\n",
        "            encoding=\"utf-8\"\n",
        "\n",
        "        ) as file:\n",
        "\n",
        "\n",
        "            json.dump(\n",
        "\n",
        "                history,\n",
        "\n",
        "                file,\n",
        "\n",
        "                indent=4,\n",
        "\n",
        "                ensure_ascii=False\n",
        "\n",
        "            )"
      ],
      "metadata": {
        "id": "cqwLfUwSfCP3"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}